#!/usr/bin/env bash
set -euo pipefail



dstu2Resources() {
  # Not supported:
  # Location
  # Organization
  # Practitioner
  curl -s http://localhost:8090/dstu2/metadata | jq .rest[].resource[].type -r | grep -Ev '(Location|Organization|Practitioner)'
}

r4Resources() {
  curl -s http://localhost:8090/r4/metadata | jq .rest[].resource[].type -r
}


urlPatternFor() {
  local pattern='.*/(metadata'
  for resource in $@; do pattern+="|${resource}"; done
  pattern+=")[?/].*"
  echo -n "$pattern"
}


if [ -n "${1:-}" ]; then FHIR_VERSION="$1"; fi
if [ -z "${FHIR_VERSION:-}" ]; then FHIR_VERSION=dstu2; fi

case ${FHIR_VERSION} in
  dstu2)
    URL_REPLACE=http://localhost:8090/dstu2
    ALLOW_QUERY_URL_PATTERN="$(urlPatternFor $(dstu2Resources))"
    ;;
  r4)
    URL_REPLACE=http://localhost:8090/r4
    ALLOW_QUERY_URL_PATTERN="$(urlPatternFor $(r4Resources))"
    ;;
  *) echo "Unknown FHIR version: $FHIR_VERSION"; exit 1;;
esac

mvn \
  -P'!standard' \
  -Dgroups=gov.va.api.health.sentinel.categories.Manual \
  -Dtest="*MagicPatientCrawl*" \
  -Daccess-token=not-used \
  -Dsentinel=LOCAL \
  -Dcrawler.base-url=http://localhost:8090/${FHIR_VERSION} \
  -Dsentinel.dstu2.url=http://localhost:8090/ \
  -Dsentinel.r4.url=http://localhost:8090/ \
  -Dcrawler.url.replace="${URL_REPLACE}" \
  -Dcrawler.allow-query-url-pattern="${ALLOW_QUERY_URL_PATTERN}" \
  -Dpatient-id=${PATIENT:-32000225} \
  -Dcrawler.timelimit=${TIME_LIMIT:-} \
  test
