#!/usr/bin/env bash

cd $(dirname $(readlink -f $0))

usage() {
cat <<EOF
$0 [options] [email|user-id]

Performs OAuth login for lab users and prints their login ID and an access token.
See all-lab-users.txt for valid email addresses or user ids.

Options
-h, --help   Print this help and exit

$1
EOF
exit 1
}

[ "$1" == "-h" -o "$1" == "--help" ] && usage

#
# Log in a user and print it's access token
#
OUTPUT=$(mktemp -p . oauth-login.XXXX)
onExit() { rm $OUTPUT; }
trap onExit EXIT

LAB_USER="$1"
FILTER=" "


if [ -n "$LAB_USER" ]
then
  if [[ "$LAB_USER" != *@* ]]
  then
    LAB_USER=$(grep -E "gmail.com $LAB_USER\$" all-lab-users.txt | cut -d ' ' -f 1)
    if [ -z "$LAB_USER" ]
    then
      usage "Did not find email address for user $1"
    fi
  fi
  LOGIN_ARGS="-Dlab.user=$LAB_USER"
  FILTER="$LAB_USER"
fi

mvn -P'!standard' test \
  -Dgroups= \
  -Dtest="*OauthLogin*" \
  $LOGIN_ARGS \
  > $OUTPUT 2>&1

USERS_FILE=lab-users.txt

[ ! -f $USERS_FILE ] \
  && echo "Missing $USERS_FILE, something terrible has happened" \
  && cat $OUTPUT \
  && exit 1


cat $USERS_FILE | cut -d ' ' -f 1,6 | grep -F "$FILTER"
cat $USERS_FILE | awk '{print "LAB_EMAIL=\"" $1 "\""; print "LAB_USER=\"" $4 "\""; print "LAB_TOKEN=\"" $6 "\""}' > lab-user.conf
